# Sample configuration file for Stompkiq.
# Options here can still be overridden by cmd line args.
#   stompkiq -C config.yml
---
:verbose: false
:concurrency:  25
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]
