source :rubygems

gem 'redis'
gem 'multi_json'
gem 'stompkiq', :git => 'git@github.com:Terenine/stompkiq.git'

group :development, :test do
  gem "rspec", "~> 2.0"
  gem 'guard'
  gem 'guard-rspec'
end

