source :rubygems

gem 'activerecord'
gem 'activerecord-sqlserver-adapter'
gem 'configuration'
gem 'foreman'
gem 'logging'
gem 'multi_json'
gem 'redis'
gem 'stompkiq', :git => 'git@github.com:Terenine/stompkiq.git'
gem 'tiny_tds'
gem 'uuidtools'

group :development, :test do
  gem "rspec", "~> 2.0"
  gem 'guard'
  gem 'guard-rspec'
end

